version: "3.7"
services:
  postgres:
    image: kartoza/postgis:12.1
    network_mode: bridge
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=massalia_user
      - POSTGRES_PASS=p
      - POSTGRES_DBNAME=massalia_test_industry
      - POSTGRES_MULTIPLE_EXTENSIONS=pgcrypto,postgis,postgis_topology
      - EXTRA_CONF=log_statement = 'all'